var list=document.getElementsByClassName('nav')[0].getElementsByTagName("li");
list[0].className="nav_active";
function change(e){
	for(var i=0;i<list.length;i++){
		list[i].className="";
	}
	e.className="nav_active";
}
function changecolor(e){
	for(var i=0;i<list.length;i++){
		list[i].style.backgroundColor="white";
	}
	e.style.backgroundColor="#0080FF";
}
$(document).ready(function(){
		$('#sure').click(function(){
			$.ajax({
				type:"POST",
				url:"index.php",
				dataType:"json",
				data:{
					chinese:$('#chinese').val(),
					english:$('#english').val(),
					action:1,
				},
				success:function(data){
				if(data.success){
					$("#ifRight").html(data.msg);
				}
				else{
					$("#ifRight").html("出现错误:"+data.msg);
				}
			},
				error:function(jqXHR,error){
				console.log(error);
			}
			});
		});
		$('#sure_2').click(function(){
      $.ajax({
        type:"POST",
        url:"index.php",
        dataType:"json",
        data:{
          chinese2:$('#chinese_2').val(),
          english2:$('#english_2').val(),
        },
        success:function(data){
        if(data.success){
          $("#display").html(data.msg);
		  var content = data.content.split(";");
		  console.log(content);
		  //为错题本列表添加数值
        }
        else{
          $("#display").html("出现错误:"+data.msg);
        }
      },
        error:function(jqXHR,error){
        console.log(error);
      }
      });
    });
	$('#sure_3').click(function(){
      $.ajax({
        type:"POST",
        url:"index.php",
        dataType:"json",
        data:{
          summary:$('#summary').val(),
        },
        success:function(data){
        if(data.success){
          $("#display_2").html(data.msg);
        }
        else{
          $("#display_2").html("出现错误:"+data.msg);
        }
      },
        error:function(jqXHR,error){
        console.log(error);
      }
      });
    });
	$('#next').click(function(){
      $.ajax({
        type:"POST",
        url:"index.php",
        dataType:"json",
        data:{
          chinese:$('#chinese').val(),
        },
        success:function(data){
        if(data.success){
          $("#ifRight").html(data.msg);
		  $("#chinese").val(data.question);
        }
        else{
          $("#ifRight").html("出现错误:"+data.msg);
        }
      },
        error:function(jqXHR,error){
        console.log(error);
      }
      });
    });
	
	});